<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/bootstrap.min.css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/fullcalendar.css">
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/app.css">	
<script src="${pageContext.request.contextPath}/js/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/js/bootstrap.min.js"></script>
<script src="${pageContext.request.contextPath}/js/moment.min.js"></script>
<script src="${pageContext.request.contextPath}/js/fullcalendar.js"></script>
<link rel="stylesheet"
	href="${pageContext.request.contextPath}/css/jquery-ui.css">	
<script src="${pageContext.request.contextPath}/js/jquery-ui.min.js"></script>